app/instructor/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed

from werkzeug import secure_filename

from wtforms import ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.fields import (
    HiddenField,
    StringField,
    SubmitField,
)
from wtforms.fields.html5 import DateField, EmailField
from wtforms.validators import (
    Email,
    EqualTo,
    InputRequired,
    Length
)

from app import db
from app.models import Student, Cohort
from app.utils import RequiredIfNot


class ChangeStudentEmailForm(FlaskForm):
    email = EmailField(
        'New email', validators=[InputRequired(),
                                 Length(1, 64),
                                 Email()])
    submit = SubmitField('Update email')

    def validate_email(self, field):
        if Student.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')


class ChangeStudentCohortForm(FlaskForm):
    cohort = QuerySelectField(
        'Cohort Name',
        validators=[],
        get_label='name',
        query_factory=lambda: db.session.query(Cohort).order_by(Cohort.start_date.desc()))

    submit = SubmitField('Update Cohort')


class NewCohortForm(FlaskForm):
    # TODO: coach selector

    cohort_slug = StringField(
        'Cohort slug', validators=[InputRequired(),
                                   Length(1, 64)])
    cohort_name = StringField(
        'Cohort name', validators=[InputRequired(),
                                   Length(1, 64)])

    start_date = DateField(
        'Start Date',
        format='%Y-%m-%d',
        validators=[InputRequired()])
    
    graduation_date = DateField(
        'Graduation Date',
        format='%Y-%m-%d',
        validators=[InputRequired()])

    submit = SubmitField('Create')

    def validate_slug(self, field):
        if Cohort.query.filter_by(slug=field.data).first():
            raise ValidationError('Cohort already created.')


class NewStudentForm(FlaskForm):

    roster = FileField(
        "Upload Roster for Single Cohort. Format expected is the output from "
        "<a href='https://learn.co/batches'>https://learn.co/batches</a>",
        validators=[FileAllowed(['csv'])])

    first_name = StringField(
        'First Name', validators=[RequiredIfNot('roster'),
                                  Length(1, 64)])
    last_name = StringField(
        'Last Name', validators=[RequiredIfNot('roster'),
                                 Length(1, 64)])

    email = EmailField(
        'Email Address', validators=[RequiredIfNot('roster'),
                                     Length(1, 64),
                                     Email()])

    cohort = QuerySelectField(
        'Cohort Name (optional)',
        validators=[],
        get_label='name',
        query_factory=lambda: db.session.query(Cohort).order_by(Cohort.start_date.desc()),
        allow_blank=True, blank_text='No Cohort')

    submit_button = SubmitField('Create')

    def validate_email(self, field):
        if Student.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')


class StudentUploadForm(FlaskForm):

    cohort = QuerySelectField(
        'Cohort Name',
        validators=[InputRequired()],
        get_label='name',
        query_factory=lambda: db.session.query(Cohort).order_by(Cohort.start_date.desc()))

    students = HiddenField()

    submit = SubmitField('Create')

app/admin/views.py
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from flask_rq import get_queue

from app import db
from app.admin.forms import (
    ChangeAccountTypeForm,
    ChangeUserEmailForm,
    InviteUserForm,
    NewUserForm,
)
from app.decorators import admin_required
from app.email import send_email
from app.models import EditableHTML, Role, User

admin = Blueprint('admin', __name__)


@admin.route('/')
@login_required
@admin_required
def index():
    """Admin dashboard page."""
    return render_template('admin/index.html')


@admin.route('/new-user', methods=['GET', 'POST'])
@login_required
@admin_required
def new_user():
    """Create a new user."""
    form = NewUserForm()
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User {} successfully created'.format(user.full_name()),
              'form-success')
    return render_template('admin/new_user.html', form=form)


@admin.route('/invite-user', methods=['GET', 'POST'])
@login_required
@admin_required
def invite_user():
    """Invites a new user to create an account and set their own password."""
    form = InviteUserForm()
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        invite_link = url_for(
            'account.join_from_invite',
            user_id=user.id,
            token=token,
            _external=True)
        get_queue().enqueue(
            send_email,
            recipient=user.email,
            subject='You Are Invited To Join',
            template='account/email/invite',
            user=user,
            invite_link=invite_link,
        )
        flash('User {} successfully invited'.format(user.full_name()),
              'form-success')
    return render_template('admin/new_user.html', form=form)


@admin.route('/users')
@login_required
@admin_required
def registered_users():
    """View all registered users."""
    users = User.query.all()
    roles = Role.query.all()
    return render_template(
        'admin/registered_users.html', users=users, roles=roles)


@admin.route('/user/<int:user_id>')
@admin.route('/user/<int:user_id>/info')
@login_required
@admin_required
def user_info(user_id):
    """View a user's profile."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/change-email', methods=['GET', 'POST'])
@login_required
@admin_required
def change_user_email(user_id):
    """Change a user's email."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    form = ChangeUserEmailForm()
    if form.validate_on_submit():
        user.email = form.email.data
        db.session.add(user)
        db.session.commit()
        flash('Email for user {} successfully changed to {}.'.format(
            user.full_name(), user.email), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route(
    '/user/<int:user_id>/change-account-type', methods=['GET', 'POST'])
@login_required
@admin_required
def change_account_type(user_id):
    """Change a user's account type."""
    if current_user.id == user_id:
        flash('You cannot change the type of your own account. Please ask '
              'another administrator to do this.', 'error')
        return redirect(url_for('admin.user_info', user_id=user_id))

    user = User.query.get(user_id)
    if user is None:
        abort(404)
    form = ChangeAccountTypeForm()
    if form.validate_on_submit():
        user.role = form.role.data
        db.session.add(user)
        db.session.commit()
        flash('Role for user {} successfully changed to {}.'.format(
            user.full_name(), user.role.name), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route('/user/<int:user_id>/delete')
@login_required
@admin_required
def delete_user_request(user_id):
    """Request deletion of a user's account."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/_delete')
@login_required
@admin_required
def delete_user(user_id):
    """Delete a user's account."""
    if current_user.id == user_id:
        flash('You cannot delete your own account. Please ask another '
              'administrator to do this.', 'error')
    else:
        user = User.query.filter_by(id=user_id).first()
        db.session.delete(user)
        db.session.commit()
        flash('Successfully deleted user %s.' % user.full_name(), 'success')
    return redirect(url_for('admin.registered_users'))


@admin.route('/_update_editor_contents', methods=['POST'])
@login_required
@admin_required
def update_editor_contents():
    """Update the contents of an editor."""

    edit_data = request.form.get('edit_data')
    editor_name = request.form.get('editor_name')

    editor_contents = EditableHTML.query.filter_by(
        editor_name=editor_name).first()
    if editor_contents is None:
        editor_contents = EditableHTML(editor_name=editor_name)
    editor_contents.value = edit_data

    db.session.add(editor_contents)
    db.session.commit()

    return 'OK', 200

app/instructor/__init__.py
from app.instructor.views import instructor  # noqa

app/instructor/views.py
import csv
from io import StringIO

from flask import (
    Blueprint,
    Markup,
    abort,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for
)
from flask_login import current_user, login_required
from flask_rq import get_queue
from werkzeug.utils import secure_filename

from app import db
from app.instructor.forms import (
    ChangeStudentCohortForm,
    ChangeStudentEmailForm,
    NewCohortForm,
    NewStudentForm,
    StudentUploadForm
)
from app.models import Student, Cohort, IDCard

instructor = Blueprint('instructor', __name__)


@instructor.route('/')
@login_required
def index():
    """Instructor dashboard page."""
    return render_template('instructor/index.html')


@instructor.route('/cohorts')
@login_required
def registered_cohorts():
    """View all registered users."""
    cohorts = Cohort.query.all()
    return render_template(
        'instructor/registered_cohorts.html', cohorts=cohorts)


@instructor.route('/new-cohort', methods=['GET', 'POST'])
@login_required
def new_cohort():
    """Create a new cohort."""
    form = NewCohortForm()
    if form.validate_on_submit():
        cohort = Cohort(
            name=form.cohort_name.data,
            slug=form.cohort_slug.data,
            start_date=form.start_date.data,
            graduation_date=form.graduation_date.data)
        db.session.add(cohort)
        db.session.commit()
        flash('Cohort {} successfully created'.format(cohort.name),
              'form-success')
    return render_template('instructor/new_cohort.html', form=form)

@instructor.route('/new-idcards')
@login_required
def register_idcards():
    """View all unregistered ID cards."""
    idcards = IDCard.query.all()
    return render_template(
        'instructor/stranded_idcards.html', idcards=idcards)


@instructor.route('/students')
@login_required
def registered_students():
    """View all registered users."""
    students = Student.query.all()
    students.sort(key=lambda s: (s.cohort and s.cohort.name) or ' ',
                  reverse=True)
    cohorts = Cohort.query.all()
    return render_template(
        'instructor/registered_students.html', students=students, cohorts=cohorts)


@instructor.route('/new-student', methods=['GET', 'POST'])
@login_required
def new_student():
    """Upload a list of students."""
    form = NewStudentForm()
    if form.validate_on_submit():
        if form.roster.data:
            roster_data = form.roster.data.read().decode('utf-8')
            first_line = roster_data.split('\n')[0]
            required_keys = ['first_name',
                             'last_name',
                             'email']
            if all(x in first_line for x in required_keys):
                session['rostercsv'] = roster_data
                return redirect(url_for('.show_uploaded_students'))

            msg = Markup('Missing fields in form. CSV header requires "first_name", "last_name", and "email"'
                         '<br>Fields received: <ul><li>{}</li></ul>'.format('</li><br><li>'.join(first_line.split(','))))
            flash(msg, 'form-error')
        elif form.first_name.data:
            student = Student(
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                email=form.email.data,
                cohort=form.cohort.data)
            db.session.add(student)
            db.session.commit()
            msg = Markup(f'Student <b>{form.first_name.data} {form.last_name.data}</b> successfully created')
            flash(msg, 'success')
            return redirect(url_for('.registered_students'))
    return render_template('instructor/new_student.html', form=form)


@instructor.route('/upload-students', methods=['GET', 'POST'])
@login_required
def show_uploaded_students():
    """Show & select uploaded students."""

    form = StudentUploadForm()
    roster = session.get('rostercsv', '')
    reader = csv.DictReader(StringIO(roster))

    students = []
    for ix, row in enumerate(reader):
        student = Student(
            first_name=row['first_name'],
            last_name=row['last_name'],
            email=row['email'])
        # invalidate students whose emails are already registered
        student.invalid = bool(Student.query.filter_by(email=row['email']).first())
        # for selecting which students to include - probably a better way of doing this
        student.index = ix
        students.append(student)

    if form.validate_on_submit():
        # student indices come in pipe delimited
        student_ix_to_add = [int(x) for x in form.students.data.split('|') if x]

        for s in [students[i] for i in student_ix_to_add]:
            s.cohort = form.cohort.data
            db.session.add(s)
        db.session.commit()
        flash('{} students successfully created'.format(len(student_ix_to_add)),
              'success')
        return redirect(url_for('.registered_students'))
    return render_template('instructor/upload_students.html', form=form, students=students)


@instructor.route('/student/<int:student_id>')
@instructor.route('/student/<int:student_id>/info')
@login_required
def student_info(student_id):
    """View a user's profile."""
    student = Student.query.filter_by(id=student_id).first()
    if student is None:
        abort(404)
    return render_template('instructor/manage_student.html', student=student)


@instructor.route('/student/<int:student_id>/change-email', methods=['GET', 'POST'])
@login_required
def change_student_email(student_id):
    """Change a student's email."""
    student = Student.query.filter_by(id=student_id).first()
    if student is None:
        abort(404)
    form = ChangeStudentEmailForm()
    if form.validate_on_submit():
        student.email = form.email.data
        db.session.add(student)
        db.session.commit()
        flash('Email for student {} successfully changed to {}.'.format(
            student.full_name(), student.email), 'form-success')
    return render_template('instructor/manage_student.html', student=student, form=form)


@instructor.route('/student/<int:student_id>/change-cohort', methods=['GET', 'POST'])
@login_required
def change_student_cohort(student_id):
    """Change a student's email."""
    student = Student.query.filter_by(id=student_id).first()
    if student is None:
        abort(404)
    form = ChangeStudentCohortForm()
    if form.validate_on_submit():
        student.cohort = form.cohort.data
        db.session.add(student)
        db.session.commit()
        flash('{} successfully moved to cohort {}.'.format(
            student.full_name(), student.cohort.name), 'success')
        return redirect(url_for('.student_info', student_id=student_id))
    return render_template('instructor/manage_student.html', student=student, form=form)


@instructor.route('/student/<int:student_id>/delete')
@login_required
def delete_student_request(student_id):
    """Request deletion of a student."""
    student = Student.query.filter_by(id=student_id).first()
    if student is None:
        abort(404)
    return render_template('instructor/manage_student.html', student=student)


@instructor.route('/student/<int:student_id>/_delete')
@login_required
def delete_student(student_id):
    """Delete a student."""
    student = Student.query.filter_by(id=student_id).first()
    db.session.delete(student)
    db.session.commit()
    flash('Successfully deleted student %s.' % student.full_name(), 'success')
    return redirect(url_for('.registered_students'))

app/templates/instructor/manage_student.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% set deletion_endpoint = 'instructor.delete_student_request' %}

{% set endpoints = [
    ('instructor.student_info', 'Student information'),
    ('instructor.change_student_email', 'Change email address'),
    ('instructor.change_student_cohort', 'Change cohort'),
    (deletion_endpoint, 'Delete student')
] %}

{% macro navigation(items) %}
    <div class="ui vertical fluid secondary menu">
        {% for route, name in items %}
            {% set href = url_for(route, student_id=student.id) %}
            <a class="item {% if request.endpoint == route %}active{% endif %}" href="{{ href }}">
                {{ name }}
            </a>
        {% endfor %}
    </div>
{% endmacro %}

{% macro student_info(student) %}
    <table class="ui compact definition table">
        <tr><td>Full name</td><td>{{ '%s %s' % (student.first_name, student.last_name) }}</td></tr>
        <tr><td>Email address</td><td>{{ student.email }}</td></tr>
        <tr><td>ID Card Number</td><td>{{ student.idcard.serial_no }}</td></tr>
        <tr><td>Cohort Name</td><td>{{ student.cohort.name }}</td></tr>
    </table>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('instructor.registered_students') }}">
                <i class="caret left icon"></i>
                Back to all students
            </a>
            <h2 class="ui header">
                {{ student.full_name() }}
                <div class="sub header">View and manage {{ student.first_name }}’s info.</div>
            </h2>
        </div>
        <div class="stretched divided very relaxed row">
            <div class="four wide column">
                {{ navigation(endpoints) }}
            </div>
            <div class="eight wide column">
                {% if request.endpoint == deletion_endpoint %}
                    <h3 class="ui red block header">
                        <i class="warning circle icon"></i>
                        <div class="content">
                            This action is permanent
                            <div class="sub header">
                                Deleting a student is not a reversible change. Any information associated
                                with this student will be removed, and cannot be recovered.
                            </div>
                        </div>
                    </h3>

                    <div class="ui form">
                        <div class="inline field">
                            <div class="ui deletion checkbox">
                                <input type="checkbox" tabindex="0" class="hidden">
                                <label>I understand that this action cannot be undone.</label>
                            </div>
                        </div>
                        <a class="ui disabled negative deletion button">
                            Delete this student
                        </a>
                    </div>
                    </div>
                {% elif form %}
                    {{ f.render_form(form) }}
                {% else %}
                    {{ student_info(student) }}
                {% endif %}
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $('.deletion.checkbox').checkbox({
            onChecked: function() {
                $('.deletion.button').removeClass('disabled')
                        .attr('href', '{{ url_for('instructor.delete_student', student_id=student.id) }}');
            },
            onUnchecked: function() {
                $('.deletion.button').addClass('disabled').removeAttr('href');
            }
        });
    </script>
{% endblock %}

app/templates/instructor/new_cohort.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('instructor.index') }}">
                <i class="caret left icon"></i>
                Back to dashboard
            </a>
            <h2 class="ui header">
                Add New Cohort
                <div class="sub header">Create a new cohort</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-slug']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

                <div class="two fields">
                    {{ f.render_form_field(form.cohort_slug) }}
                    {{ f.render_form_field(form.cohort_name) }}
                </div>

                <div class="two fields">
                    {{ f.render_form_field(form.start_date) }}
                    {{ f.render_form_field(form.graduation_date) }}
                </div>
                TODO: add default coaches/instructors

                {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                {{ f.form_message(flashes['warning'], header='Warning', class='warning') }}
                {{ f.form_message(flashes['info'], header='Information', class='info') }}
                {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                    {{ f.render_form_field(field) }}
                {% endfor %}

            {{ f.end_form() }}
        </div>
    </div>
{% endblock %}

app/templates/instructor/registered_students.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui stackable grid container">
        <div class="sixteen wide tablet twelve wide computer centered column">
            <a class="ui basic compact button" href="{{ url_for('instructor.index') }}">
                <i class="caret left icon"></i>
                Back to dashboard
            </a>
            <h2 class="ui header">
                Registered Students
                <div class="sub header">
                    View and manage currently registered students.
                </div>
            </h2>

            <div class="ui menu">
                <div id="select-cohort" class="ui dropdown item">
                    <div class="text">
                        All cohorts
                    </div>
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <div class="item" data-value="">All cohorts</div>
                        {% for c in cohorts %}
                            <div class="item" data-value="{{ c.name }}">{{ c.name }}</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="ui right search item">
                    <div class="ui transparent icon input">
                        <input id="search-students" type="text" placeholder="Search students…">
                        <i class="search icon"></i>
                    </div>
                </div>
            </div>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable celled table">
                    <thead>
                        <tr>
                            <th>First name</th>
                            <th>Last name</th>
                            <th>Email address</th>
                            <th>ID Card</th>
                            <th>Cohort</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for s in students %}
                        <tr onclick="window.location.href = '{{ url_for('instructor.student_info', student_id=s.id) }}';">
                            <td>{{ s.first_name }}</td>
                            <td>{{ s.last_name }}</td>
                            <td>{{ s.email }}</td>
                            <td>{{ s.idcard.serial_no }}</td>
                            <td class="student cohort">{{ s.cohort.name }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-students').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-cohort').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('td.student.cohort:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('td.student.cohort').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}

app/templates/instructor/upload_students.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="sixteen wide tablet twelve wide computer centered column">
            <a class="ui basic compact button" href="{{ url_for('instructor.index') }}">
                <i class="caret left icon"></i>
                Back to dashboard
            </a>
            <h2 class="ui header">
                Upload New Students
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-slug']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Warning', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {{ f.render_form_field(form.cohort) }}
            <div class="sub header">
                New cohort? <a href="{{ url_for('instructor.new_cohort') }}">Add the cohort</a> first.
            </div>
            <p />

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui sortable unstackable selectable celled table definition">
                    <thead>
                        <tr>
                            <th></th>
                            <th>First name</th>
                            <th>Last name</th>
                            <th>Email address</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for s in students %}
                        <tr class="{{'negative' if s.invalid }}">
                            <td class="collapsing">
                                <div class="ui fitted toggle checkbox{{ ' checked' if not s.invalid }}">
                                    <input name="student_include" value="{{ s.index }}"
                                           type="checkbox"{{ ' disabled' if s.invalid else ' checked' }}>
                                    <label></label>
                                </div>
                            </td>
                            <td>{{ s.first_name }}</td>
                            <td>{{ s.last_name }}</td>
                            <td>{{ s.email }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <p />

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}
            {{ f.end_form() }}

        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('form').submit(function() {
                var arr=[];
                $('input:checked[name=student_include]').each(function () {
                    arr.push($(this).val());
                });

                $('#students').val(arr.join('|'));
            });

            $("table tbody").on("click", "tr", function(e) {
                if ($(e.target).is("label,input")) {
                    return
                } else {
                    var inp = this.getElementsByTagName('input')[0];
                    if (inp.disabled == false) {
                        inp.checked = !inp.checked
                    };
                }
            });
        });
    </script>

{% endblock %}